# This GitHub Action creates the dinghy digest and publishes them every day.

name: "Daily activity digests"

on:
  push:
  schedule:
    # noon-ish UTC, so 7/8am Eastern.
    # https://crontab.guru/#0_7_%2A_%2A_%2A
    - cron: "0 7 * * *"
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  digest:
    name: "Daily digest"
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3

      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: "Install dinghy"
        run: |
          python -m pip install dinghy

      - name: "Run dinghy"
        env:
          # Made with nedbat's account, with public_repo, read:org, read:project
          GITHUB_TOKEN: ${{ secrets.DINGHY_ACCESS_TOKEN }}
        run: |
          python -m dinghy --verbosity=debug || \
          python -m dinghy --verbosity=debug || \
          exit 1

      - name: "Setup Pages"
        uses: actions/configure-pages@v2

      - name: "Upload artifact"
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'

      - name: "Deploy to GitHub Pages"
        uses: actions/deploy-pages@v1
