# This GitHub Action creates dinghy digests and publishes them.

name: "Create and publish digests"

on:
  workflow_call:
    inputs:
      config:
        required: true
        type: string
    secrets:
      token:
        required: true

defaults:
  run:
    shell: bash

env:
  CONFIG: ${{ inputs.config }}

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "digest"
  cancel-in-progress: true

jobs:
  digest:
    name: "Daily digest"
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}

      - name: "Install Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "Install dinghy"
        run: |
          python -m pip install dinghy

      - name: "Run dinghy"
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        run: |
          python -m dinghy --verbosity=debug $CONFIG || \
          python -m dinghy --verbosity=debug $CONFIG || \
          exit 1

      - name: "Push digests to pages"
        run: |
          git config user.name nedbat
          git config user.email ned@nedbatchelder.com
          git add *.html
          git status
          git stash
          git fetch --all
          git checkout pages
          git checkout stash -- .
          git status
          git commit -m "latest digests from $CONFIG"
          git push
