# This GitHub Action creates dinghy digests and publishes them every day.

name: "Daily activity digests: docs"

on:
  schedule:
    # noon-ish UTC, so 7/8am Eastern.
    # https://crontab.guru/#0_7_%2A_%2A_%2A
    - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  digest:
    name: "Daily digest"
    uses: ./.github/workflows/daily-digest.yml
    with:
      config: docs.yaml
    secrets:
      # Made with nedbat's account, with repo, read:org, read:project
      # https://github.com/settings/tokens/943640357
      token: ${{ secrets.DINGHY_ACCESS_TOKEN }}
