# This GitHub Action creates dinghy digests and publishes them every day.

name: "Daily activity digests: ospwg"

on:
  schedule:
    # noon-ish UTC, so 7/8am Eastern.
    # https://crontab.guru/#0_7_%2A_%2A_%2A
    - cron: "0 7 * * *"
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  digest:
    name: "Daily digest"
    uses: ./.github/workflows/daily-digest.yml
    with:
      config: ospwg.yaml
    secrets:
      # Made with nedbat's account, with public_repo, read:org, read:project
      token: ${{ secrets.DINGHY_ACCESS_TOKEN }}
