# This GitHub Action creates a test dinghy digest and publishes it.

name: "Daily activity digests: test"

on:
  push:
    branches-ignore:
      - pages
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  digest:
    name: "Daily digest"
    uses: ./.github/workflows/daily-digest.yml
    with:
      config: test.yaml
    secrets:
      # Made with nedbat's account, with repo, read:org, read:project
      # https://github.com/settings/tokens/943640357
      token: ${{ secrets.DINGHY_ACCESS_TOKEN }}
